TARGET = cd

CROSS_COMPILE =

CC = $(CROSS_COMPILE)arm-linux-g++

OBJS = config.o input.o video.o font.o decoder.o audio.o cd.o main.o

VPATH = ./

CFLAGS = -I. -O2 -march=armv5te -mtune=arm926ej-s `sdl-config --cflags` -DMIYOO

LDFLAGS = `sdl-config --libs` -lasound -lSDL_ttf

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $@
	@echo Done!!!

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f *.o $(TARGET) $(TARGET).ipk